  - id: "1"
    name: "Marketbag - Large"
    coverImage: "./marketbag_large/gallery.jpg"
  - id: "2"
    name: "Marketbag - Small"
    coverImage: "./marketbag_small/gallery.jpg"
  - id: "3"
    name: "Linen Kitchen Towel"
    coverImage: "./hangingtowel_linen/gallery.jpg"
  - id: "4"
    name: "Potholder"
    coverImage: "./potholder/gallery.jpg"
  - id: "5"
    name: "Scrubbie"
    coverImage: "./scrubbie/gallery.jpg"
  - id: "6"
    name: "Spinner"
    coverImage: "./spinner/gallery.jpg"